name: ENNOS_Organoid
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.7.15
  - expat=2.7.1
  - libffi=3.4.4
  - openssl=3.0.17
  - pip=25.2
  - python=3.12.11
  - setuptools=78.1.1
  - sqlite=3.50.2
  - tk=8.6.15
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - colorama==0.4.6
      - contourpy==1.3.3
      - cycler==0.12.1
      - filelock==3.13.1
      - fonttools==4.59.2
      - fsspec==2024.6.1
      - jinja2==3.1.4
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - markupsafe==2.1.5
      - matplotlib==3.10.6
      - mpmath==1.3.0
      - networkx==3.3
      - numpy==2.1.2
      - opencv-python==4.12.0.88
      - packaging==25.0
      - pillow==11.0.0
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - scikit-learn==1.7.1
      - scipy==1.16.1
      - six==1.17.0
      - sympy==1.13.1
      - threadpoolctl==3.6.0
      - torch==2.6.0+cu124
      - torchaudio==2.6.0+cu124
      - torchvision==0.21.0+cu124
      - tqdm==4.67.1
      - typing-extensions==4.12.2
